export enum TournamentActionTypes {
    STORE_TOURNAMENTS = 'TOURNAMENT/STORE_TOURNAMENTS',
    EDIT_TOURNAMENT = 'TOURNAMENT/EDIT_TOURNAMENT',
    DELETE_TOURNAMENT = 'TOURNAMENT/DELETE_TOURNAMENT'
}

export enum SearchActionTypes {
    SEARCH_TOURNAMENTS = 'SEARCH/SEARCH_TOURNAMENTS',
    SET_SEARCH_TERM = 'SEARCH/SET_SEARCH_TERM'
}
