export enum TournamentActionTypes {
    STORE_TOURNAMENTS = 'TOURNAMENT/STORE_TOURNAMENTS',
    EDIT_TOURNAMENT = 'TOURNAMENT/EDIT_TOURNAMENT',
    DELETE_TOURNAMENT = 'TOURNAMENT/DELETE_TOURNAMENT'
}
